package com.wallet.onlinewalletapplication.module;

public enum TransactionType {
	WALLET_BALANCE_UPDATED, WALLET_TO_WALLET_FUND_TRANSFER, WALLET_TO_MOBILE_RECHARGE,
	WALLET_TO_ELECTRICITY_BILL, WALLET_TO_CREDIT_CARD_PAYMENT, WALLET_TO_ACCOUNT
}
